<div class="container-fluid">
    <div>
        <h3>CHANGELOGS</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">CHANGELOGS</li>
            </ol>
        </nav>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="card-body">
                <h6 class="card-title">v1.6 <small>2022-01-12</small></h6>
                <ul>
                    <li>[Added] FFMPEG debugger.</li>
                    <li>[Added] SMTP debugger.</li>
                    <li>[Added] Flutterwave payment method.</li>
                    <li>[Added] wasabi storage system. </li>
                    <li>[Added] backblaze storage system. </li>
                    <li>[Added] the ability to choose withdrawal method. </li>
                    <li>[Added] developer mode to admin panel. </li>
                    <li>[Added] the ability to set minimum withdrawal request.</li>
                    <li>[Added] Yoomoney payment method.</li>
                    <li>[Added] login with TikTok.</li>
                    <li>[Added] the ability to create and generate sitemap.</li>
                    <li>[Added] the ability to import reels from TikTok.</li>
                    <li>[Added] Google Vision API to filter nude posts.</li>
                    <li>[Added] two authentication system.</li>
                    <li>[Added] CDN support.</li>
                    <li>[Added] the support to translate terms of use pages.</li>
                    <li>[Added] the ability to disable terms pages.</li>
                    <li>[Added] 3 SMS providers.</li>
                    <li>[Added] FFMPEG conversation speed settings.</li>
                    <li>[Added] support for image/webp.</li>
                    <li>[Added] more APIs.</li>
                    <li>[Updated] All PHP libs.</li>
                    <li>[Fixed] sharing posts with hashtags appear distorted on the main feed.</li>
                    <li>[Fixed] the avatar on the profile page shows double url and cannot be displayed once remote storage like amazon s3 is turned on.</li>
                    <li>[Fixed] If amazon s3 enabled gifs appear broken.</li>
                    <li>[Fixed] showing broken social links in settings page.</li>
                    <li>[Fixed] agora live and video calls.</li>
                    <li>[Fixed] few issues in blog system.</li>
                    <li>[Fixed] explore page showing old posts if there are boosted posts.</li>
                    <li>[Fixed] if s3 is enabled, social login doesn't work.</li>
                    <li>[Fixed] user can't resend </li>
                    <li>[Fixed] can't change "Boosted Post" value from admin panel.</li>
                    <li>[Fixed] contact us form not sending emails.</li>
                    <li>[Fixed] only first Navigation works in "Manage Site Advertisements" in admin panel.</li>
                    <li>[Fixed] copy and paste using right click doesn't work in admin panel.</li>
                    <li>[Fixed] some files are loaded remotly, now all files are loaded from the same server.</li>
                    <li>[Fixed] can't login to site again if maintenance mode is enabled + two auth.</li>
                    <li>[Fixed] email validation system, user was getting empty string in email.</li>
                    <li>[Fixed] files are not deleting from Digitalocean.</li>
                    <li>[Fixed] coinpayments system.</li>
                    <li>[Fixed] can't edit languages from admin panel.</li>
                    <li>[Fixed] when user share a locked post, it shows unlocked on user's profile for everyone to see.</li>
                    <li>[Fixed] Twilio calls.</li>
                    <li>[Fixed] Business accounts not getting approved.</li>
                    <li>[Fixed] If you enabled pro on sign up, all links will stop working using ajax load.</li>
                    <li>[Fixed] 20+ minor bugs</li>
                    <li>[Improved] speed.</li>
                </ul>
            </div>
        </div>
    </div>
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="card-body">
                <h6 class="card-title">v1.5 <small>2022-03-21</small></h6>
                <ul>
                    <li>[Added] LinkedIn, Vkontakte, Instagram, QQ, WeChat, Discord & Mailru social login.. </li>
                    <li>[Added] more payment methods.</li>
                    <li>[Added] Agora live & video chats. </li>
                    <li>[Added] the ability to upload 360-degree video. </li>
                    <li>[Added] the ability to unlock images and videos. (pay or subscribe) </li>
                    <li>[Added] currency system. </li>
                    <li>[Added] new admin panel, v2 .</li>
                    <li>[Added] new welcome page design.</li>
                    <li>[Added] submit button to comment box.</li>
                    <li>[Added] audio chat.</li>
                    <li>[Added] support for PHP 8.0+ and MySQL 8.0+</li>
                    <li>[Updated] default theme design.</li>
                    <li>[Fixed] 20+ reported bugs</li>
                    <li>[Improved] speed.</li>
                </ul>
            </div>
        </div>
    </div>
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">v1.4.2 <small>2021-03-25</small></h6>
                    <ul>
                        <li>[Added] live system. </li>
                        <li>[Added] more payment  methods.</li>
                        <li>[Added] reels section for videos. </li>
                        <li>[Fixed] 20+ reported bugs</li>
                        <li>[Improved] speed.</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">v1.4.1 <small>2020-07-08</small></h6>
                    <ul>
                        <li>[Fixed] few bugs</li>
                        <li>[Improved] speed.</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">v1.4 <small>2020-06-22</small></h6>
                    <ul>
                        <li>[Added] more payment methods for example paysera, indian payment gateway and paystack. </li>
                        <li>[Added] Ability to edit or delete photos from store.</li>
                        <li>[Added] Add digital ocean for storage.</li>
                        <li>[Added] ability to set and choose multi license types for store while uploading image and set price for each license type. </li>
                        <li>[Added] ability to share posts within sites. </li>
                        <li>[Added] video calls. </li>
                        <li>[Added] ability to require subscription on sign up with (enable/disable). </li>
                        <li>[Added] ability to limit storage for free users.</li>
                        <li>[Added] allow signs ups from specific Email only for example users having gmail.com ID could sign up only. </li>
                        <li>[Added] ability to post comments on blog.</li>
                        <li>[Added] ability for users could also create blogs (enable/disable). </li>
                        <li>[Added] ability to set light/dark mode by default </li>
                        <li>[Fixed] bugs</li>
                        <li>[Improved] speed.</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">v1.3 <small>2019-12-9</small></h6>
                    <ul>
                        <li>[Added] store system, users can sell images. </li>
                        <li>[Added] blog system.</li>
                        <li>[Added] new APIs.</li>
                        <li>[Fixed] bugs</li>
                        <li>[Improved] speed.</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">v1.2.1 <small>2019-07-10</small></h6>
                    <ul>
                        <li>[Added] earnigns page in admin panel. </li>
                        <li>[Fixed] bugs</li>
                        <li>[Improved] speed.</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">v1.2 <small>2019-05-07</small></h6>
                    <ul>
                        <li>[Added] like comment system.</li>
                        <li>[Added] reply to comment system. </li>
                        <li>[Added] affiliate system. </li>
                        <li>[Added] more payment methods, bank transfer, stripe.</li>
                        <li>[Added] the ability to pause the story if you click on it.</li>
                        <li>[Added] To add money in the wallet from admin panel. </li>
                        <li>[Added] Ads system for users, users now can advertise on your site.</li>
                        <li>[Added] pro system, with new profile layout. </li>
                        <li>[Added] raise money system, photographers can ask for funding and get funded by users.</li>
                        <li>[Added] business account like Instagram.</li>
                        <li>[Added] follow requests, now if profile is private, it is required to accept a follow request before viewing the posts. </li>
                        <li>[Removed] @ from user profile url. </li>
                        <li>[Organized] Admin panel, added search for some pages, select all for posts, etc. </li>
                        <li>[Updated] Password hash system from sha1 to password_hash PHP function. </li>
                        <li>[Fixed] few important bugs.</li>
                        <li>[Improved] speed.</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">v1.1.2 <small>2019-01-13</small></h6>
                    <ul>
                        <li>[Fixed] few important bugs.</li>
                        <li>[Added] New API for the new native app.</li>
                        <li>[Improved] speed.</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">v1.1.1 <small>2018-11-21</small></h6>
                    <ul>
                        <li>[Fixed] few important bugs.</li>
                        <li>[Improved] speed.</li>
                    </ul>
                </div>
            </div>
        </div>
         <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">v1.1 <small>2018-10-29</small></h6>
                    <ul>
                        <li>[Added] face filters using webcam.</li>
                        <li>[Added] watermark system on images</li>
                        <li>[Added] support for mp4 links.</li>
                        <li>[Added] night mode</li>
                        <li>[Added] url fetcher, fetch images from urls.</li>
                        <li>[Added] blacklist system, for ip, username, emails.</li>
                        <li>[Added] lazyload for explore page (loads faster)</li>
                        <li>[Added] activities system (likes, comments, follow)</li>
                        <li>[Added] the abililty for the user to choose if their profile should be found/indexed.</li>
                        <li>[Added] ReCaptcha check to forgot password form</li>
                        <li>[Added] Session manager in settings page</li>
                        <li>[Added] Contact us page</li>
                        <li>[Added] emojis support for posts and comments.</li>
                        <li>[Added] Playtube support, you can import videos from a site that uses playtube script.</li>
                        <li>[Added] verification badge & system.</li>
                        <li>[Added] report filtration/warnings system.</li>
                        <li>[Added] startup page, upload avatar, fill info, follow.</li>
                        <li>[Added] emebd system, users can emebd posts from PixelPhoto using iframe.</li>
                        <li>[Added] video views system.</li>
                        <li>[Added] ajax load for pages (now pages load without refreshing).</li>
                        <li>[Added] full API system for the upcoming native app + docs.</li>
                        <li>[Fixed] few important bugs.</li>
                        <li>[Improved] speed.</li>
                    </ul>
                </div>
            </div>
        </div>
         <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">v1.0.3 <small>2018-08-13</small></h6>
                    <ul>
                        <li>Fixed few important bugs.</li>
                    </ul>
                </div>
            </div>
        </div>
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">v1.0.2 <small>2018-07-27</small></h6>
                    <ul>
                        <li>Fixed bugs in firefox and in video thumbnail.</li>
                    </ul>
                </div>
            </div>
        </div>
         <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">v1.0.1 <small>2018-07-26</small></h6>
                    <ul>
                        <li>Fixed bugs.</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">v1.0 <small>2018-07-20</small></h6>
                    <ul>
                        <li>First release.</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
