<div class="container-fluid">
    <div>
        <h3>Affiliates Settings</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Users</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Affiliates Settings</li>
            </ol>
        </nav>
    </div>

    
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Affiliates Settings</h6>
                    <div class="form-alert affiliates-settings-alert"></div>
                    <form class="affiliates-settings" method="POST">
                        <div class="float-left">
                            <label for="affiliate_system" class="main-label">Affiliates System</label>
                            <br><small class="admin-info">Affiliates System</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="affiliate_system" value="0" />
                            <input type="checkbox" name="affiliate_system" id="chck-affiliate_system" value="1" <?php echo ($config['affiliate_system'] == '1') ? 'checked': '';?>>
                            <label for="chck-affiliate_system" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <label for="affiliate_type" class="main-label">User will earn money when</label>
                        <br><small class="admin-info">User will earn money when</small>
                        <div class="form-group">
                            <select class="form-control show-tick" id="affiliate_type" name="affiliate_type">
                                <option value="0" <?php echo ($config['affiliate_type'] == 0) ? 'selected': '';?> >New user is registred</option>
                            </select>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group">
                            <div class="form-line">
                                <label class="form-label" class="main-label">Amount</label>
                                <input type="text" name="amount_ref" class="form-control" value="<?php echo $config['amount_ref']?>"><small class="admin-info">The price you'll pay for each new referred user. Default 0.10</small>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>
$(function() {
    $('.switcher input[type=checkbox]').click(function () {
        var configName = $(this).attr('name');
        var hash_id = $('input[name=hash_id]').val();
        var objData = {};
        if ($(this).is(":checked") === true) {
            objData[configName] = $(this).val();
        }
        else{
            if ($('input[name='+configName+']')[0]) {
                objData[configName] = $($('input[name='+configName+']')[0]).val();
            }
        }
        objData['hash_id'] = hash_id;
        $.post(acpajax_url('general-settings'), objData);
    });

    var setTimeOutColor = setTimeout(function (){});
    $('select').on('change', function() {
         clearTimeout(setTimeOutColor);
        var thisElement = $(this);
        var configName = thisElement.attr('name');
        var hash_id = $('input[name=hash_id]').val();
        var objData = {};
        objData[configName] = thisElement.val();
        objData['hash_id'] = hash_id;
        thisElement.addClass('warning');
        $.post(acpajax_url('general-settings'), objData, function (data) {
            if (data.status == 200) {
                thisElement.removeClass('warning');
                thisElement.addClass('success');
            } else {
                thisElement.addClass('error');
            }
            var setTimeOutColor = setTimeout(function () {
                thisElement.removeClass('success');
                thisElement.removeClass('warning');
                thisElement.removeClass('error');
            }, 2000);
        });
    });
    $('input[type=text], input[type=number] , textarea').on('input', delay(function() {
            clearTimeout(setTimeOutColor);
            var thisElement = $(this);
            var configName = thisElement.attr('name');
            var hash_id = $('input[name=hash_id]').val();
            var objData = {};
            objData[configName] = this.value;
            objData['hash_id'] = hash_id;
            thisElement.addClass('warning');
            $.post(acpajax_url('general-settings'), objData, function (data) {
                if (data.status == 200) {
                    thisElement.removeClass('warning');
                    thisElement.addClass('success');
                } else {
                    thisElement.addClass('error');
                }
                var setTimeOutColor = setTimeout(function () {
                    thisElement.removeClass('success');
                    thisElement.removeClass('warning');
                    thisElement.removeClass('error');
                }, 2000);
                //thisElement.focus();
            });
    }, 500));
}); 
</script>