<?php 
$page                = (!empty($_GET['page-id'])) ? $_GET['page-id'] : 1;
$admin::$db->pageLimit       = 50;
$link = '';
$total      = $admin::$db->getValue(T_TRANSACTIONS, 'sum(amount)');
$admin_earn       = $admin::$db->getValue(T_TRANSACTIONS, 'sum(admin_com)');
$total = $total + $admin_earn;
$donate       = $admin::$db->where('type','donate')->getValue(T_TRANSACTIONS, 'sum(amount)');
$donate = $donate + $admin_earn;

$wallet       = $admin::$db->where('type','Advertise')->getValue(T_TRANSACTIONS, 'sum(amount)');
$pro       = $admin::$db->where('type','pro_member')->getValue(T_TRANSACTIONS, 'sum(amount)');

$transactions = $admin::$db->orderBy('id','DESC')->paginate(T_TRANSACTIONS,$page);

if (($page > $admin::$db->totalPages) && !empty($_GET['page-id'])) {
    header("Location: " . pxp_acp_link('earnings'));
    exit();
}
?>

<div class="container-fluid">
    <div>
        <h3>Earnings</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Payments & Ads</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Earnings</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Total Earnings</h6>
                    <div class="d-flex align-items-center mb-3">
                        <div>
                            <div class="avatar">
                                <span class="avatar-title bg-info-bright text-info rounded-pill">
                                    <i class="material-icons">attach_money</i>
                                </span>
                            </div>
                        </div>
                        <div class="font-weight-bold ml-1 font-size-30 ml-3"><?php echo Pxp_GetCurrency($context['config']['currency']).$total; ?></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Admin Earnings</h6>
                    <div class="d-flex align-items-center mb-3">
                        <div>
                            <div class="avatar">
                                <span class="avatar-title bg-info-bright text-info rounded-pill">
                                    <i class="material-icons">attach_money</i>
                                </span>
                            </div>
                        </div>
                        <div class="font-weight-bold ml-1 font-size-30 ml-3"><?php echo Pxp_GetCurrency($context['config']['currency']).$admin_earn; ?></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Total Donation With Commission</h6>
                    <div class="d-flex align-items-center mb-3">
                        <div>
                            <div class="avatar">
                                <span class="avatar-title bg-info-bright text-info rounded-pill">
                                    <i class="material-icons">attach_money</i>
                                </span>
                            </div>
                        </div>
                        <div class="font-weight-bold ml-1 font-size-30 ml-3"><?php echo Pxp_GetCurrency($context['config']['currency']).$donate; ?></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Total Ads Paid</h6>
                    <div class="d-flex align-items-center mb-3">
                        <div>
                            <div class="avatar">
                                <span class="avatar-title bg-info-bright text-info rounded-pill">
                                    <i class="material-icons">attach_money</i>
                                </span>
                            </div>
                        </div>
                        <div class="font-weight-bold ml-1 font-size-30 ml-3"><?php echo Pxp_GetCurrency($context['config']['currency']).$wallet; ?></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Pro Members</h6>
                    <div class="d-flex align-items-center mb-3">
                        <div>
                            <div class="avatar">
                                <span class="avatar-title bg-info-bright text-info rounded-pill">
                                    <i class="material-icons">attach_money</i>
                                </span>
                            </div>
                        </div>
                        <div class="font-weight-bold ml-1 font-size-30 ml-3"><?php echo Pxp_GetCurrency($context['config']['currency']).$pro; ?></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Earnings</h6>
                   <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                                <tr role="row">
                                    <th>ID</th>
                                    <th>Username</th>
                                    <th>Amount</th>
                                    <th>Admin Earnings</th>
                                    <th>Date</th>
                                    <th>Type</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php 
                                    foreach ($transactions as $key => $wal_requests) {
                                        $user = $admin::$db->where('user_id',$wal_requests->user_id)->getOne(T_USERS);
                                        $context['wal_requests'] = o2array($wal_requests);
                                        $context['user'] = o2array($admin->userData($user));
                                        echo $admin->loadPage('earnings/list');
                                    }
                                ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="wo-admincp-feturepager">
                      <div class="pull-left">
                        <span>
                          <?php echo "Showing $page out of " . $admin::$db->totalPages; ?>
                        </span>
                      </div>
                      <div class="pull-right">
                        <nav>
                          <ul class="pagination">
                            <li>
                              <a href="<?php echo pxp_acp_link('earnings?page-id=1').$link; ?>" data-ajax="?path=earnings&page-id=1<?php echo($link); ?>" class="waves-effect" title='First Page'>
                                  <i class="material-icons">first_page</i>
                              </a>
                            </li>
                            <?php if ($page > 1) {  ?>
                              <li>
                                  <a href="<?php echo pxp_acp_link('earnings?page-id=' . ($page - 1)).$link; ?>" data-ajax="?path=earnings&page-id=<?php echo($page - 1) ?><?php echo($link); ?>" class="waves-effect" title='Previous Page'>
                                      <i class="material-icons">chevron_left</i>
                                  </a>
                              </li>
                            <?php  } ?>

                            <?php 
                              $nums       = 0;
                              $nums_pages = ($page > 4) ? ($page - 4) : $page;

                              for ($i=$nums_pages; $i <= $admin::$db->totalPages; $i++) { 
                                if ($nums < 20) {
                            ?>
                              <li class="<?php echo ($page == $i) ? 'active' : ''; ?>">
                                <a href="<?php echo pxp_acp_link('earnings?page-id=' . ($i)).$link; ?>" data-ajax="?path=earnings&page-id=<?php echo($i) ?><?php echo($link); ?>" class="waves-effect">
                                  <?php echo $i ?>   
                                </a>
                              </li>

                            <?php } $nums++; }?>

                            <?php if ($admin::$db->totalPages > $page) { ?>
                              <li>
                                  <a href="<?php echo pxp_acp_link('earnings?page-id=' . ($page + 1)).$link; ?>" data-ajax="?path=earnings&page-id=<?php echo($page + 1) ?><?php echo($link); ?>" class="waves-effect" title="Next Page">
                                      <i class="material-icons">chevron_right</i>
                                  </a>
                              </li>
                            <?php } ?>
                            <li>
                              <a href="<?php echo pxp_acp_link('earnings?page-id=' . ($admin::$db->totalPages)).$link; ?>" data-ajax="?path=earnings&page-id=<?php echo($admin::$db->totalPages) ?><?php echo($link); ?>" class="waves-effect" title='Last Page'>
                                  <i class="material-icons">last_page</i>
                              </a>
                            </li>
                          </ul>
                        </nav>
                      </div>
                      <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>