<?php 
$privacy = $admin->getPage('privacy_and_policy');
?>
<div class="container-fluid">
    <div>
        <h3>privacy-and-policy</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Pages</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">privacy-and-policy</li>
            </ol>
        </nav>
    </div>

    <div class="row clearfix">
        <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Write privacy and policy of this website</h6>
                    <form class="form privacy-and-policy-form">
                        <div class="form-alert"></div>
                        <div class="form-group">
                            <textarea name="privacy" id="privacy-and-policy"><?php echo $privacy; ?></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    jQuery(document).ready(function($) {
        tinymce.init({
            selector: '#privacy-and-policy',
            relative_urls: false,
            remove_script_host: false,
            height:500,
            toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link | preview fullpage | forecolor backcolor emoticons',
            plugins: [
                'advlist autolink link  lists charmap  preview hr anchor spellchecker',
                'searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking',
                'save table contextmenu directionality emoticons template paste textcolor'
            ]
        });

        var privacy_form = $("form.privacy-and-policy-form");

        privacy_form.submit(function(event) {
            var text = tinymce.activeEditor.getContent({format: 'raw'});
            if (!text){
                privacy_form.find('.form-alert').html($('<div>',{
                    class:'alert alert-danger',
                    text:'Can not save changes, something went wrong Please try again'
                }));

                setTimeout(function(){
                    window.location.reload();
                });

                return false;
            }
            else{
                $("#privacy-and-policy").val(text);
            }   
        });

        privacy_form.ajaxForm({
            url: acpajax_url('privacy-and-policy'),
            type: 'POST',
            dataType: 'json',
            beforeSubmit: function(arr,form){
                arr[0]['value'] = btoa(unescape(encodeURIComponent(arr[0]['value'])));
                $(form).find('button[type=submit]').text('Please wait.').attr('disabled', 'true');
            },
            success: function(data, status, xhr, form){
                if (data.status == 200) {
                    $(form).find('.form-alert').html($('<div>',{
                        class:'alert alert-success',
                        text: data.message
                    }));
                    setTimeout(function(){
                        privacy_form.find('.form-alert .alert').slideUp('fast',function(){
                            $(this).remove(); 
                        })    
                    },3000);
                }
                else{
                    $(form).find('.form-alert').html($('<div>',{
                        class:'alert alert-warning',
                        text: data.message
                    }));
                }

                privacy_form.find('button[type=submit]').text('Save').removeAttr('disabled');
            }
        });
    });
</script>