<tr class="setting-postlist" id="<?php echo($cd['lang_key']);?>" data_selected="<?php echo($cd['lang_key']);?>">
  <td><input type="checkbox" id="check-data-<?php echo($cd['lang_key']);?>" class="delete-checkbox filled-in"><label for="check-data-<?php echo($cd['lang_key']);?>"></label></td>
   <td style="text-align: center;"><?php echo $cd['lang_name']; ?></td>
   <td style="text-align: center;">
      <a class="btn bg-success admn_table_btn" href="<?php echo pxp_acp_link("edit-language?id={$cd['lang_key']}"); ?>">Edit</a>
      <a href="javscript:void(0)" class="delete-field btn bg-danger admn_table_btn" onclick="Wo_DeleteLang('<?php echo($cd['lang_key']);?>','hide');">Delete</a>
      
   </td>
</tr>