<?php 
$ads1 = $config['ad1'];
$ads2 = $config['ad2'];
$ads3 = $config['ad3'];
$langs = $admin::getLangs();
?>
<div class="container-fluid">
    <div>
        <h3>Manage Site Advertisements</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Payments & Ads</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Manage Site Advertisements</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Manage Site Advertisements</h6>
                    <form class="form site-settings-form" method="POST">
                        <div class="form-alert"></div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Navigation <small>(Appears under the navigation menu.)</small></label>
                                <textarea name="ad1" id="ad1" class="form-control" cols="30" rows="5"><?php echo $config['ad1'];?></textarea>
                                
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Top Sidebar <small>(Appears at the top of the sidebar.)</small></label>
                                <textarea name="ad2" id="ad2" class="form-control" cols="30" rows="5"><?php echo $config['ad2'];?></textarea>
                                
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Bottom Sidebar <small>(Appears at the bottom of the sidebar.)</small></label>
                                <textarea name="ad3" id="ad3" class="form-control" cols="30" rows="5"><?php echo $config['ad3'];?></textarea>
                                
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
<script>

    jQuery(document).ready(function($) {
        var ssform = $("form.site-settings-form");

        ssform.ajaxForm({
            url: acpajax_url('ad-settings'),
            type: 'POST',
            dataType: 'json',
            beforeSubmit: function(arr,form){
                for (const index in arr) {
                    arr[index]['value'] = btoa(unescape(encodeURIComponent(arr[index]['value'])));
                }
                $(form).find('button[type=submit]').text('Please wait.').attr('disabled', 'true');
            },
            success: function(data, status, xhr, form){
                ssform.find('button[type=submit]').text('Save').removeAttr('disabled');
                if (data.status == 200) {
                    $(form).find('.form-alert').html($('<div>',{
                        class:'alert alert-success',
                        text:'Settings has been updated successfully'
                    }));
                    setTimeout(function(){
                        ssform.find('.form-alert .alert').slideUp('fast',function(){
                            $(this).remove(); 
                        })    
                    },1000);
                }
                else{
                    $(form).find('.form-alert').html($('<div>',{
                        class:'alert alert-warning',
                        text: data.error
                    }));
                }

                
            }
        });
    });
</script>