<tr id="list-<?php echo $cd['blog-categories']['category_key'];?>" data_selected="<?php echo($cd['blog-categories']['category_key']) ?>">
    <td><input type="checkbox" id="check-data-<?php echo $cd['blog-categories']['category_key'];?>" class="delete-checkbox filled-in"><label for="check-data-<?php echo $cd['blog-categories']['category_key'];?>"></label></td>
    <td><?php echo $cd['blog-categories']['category_id'];?></td>
    <td id="edit_<?php echo $cd['blog-categories']['category_key'];?>"><?php echo $cd['blog-categories']['category'];?></td>
    <td>
        <button type="button" class="btn bg-success admn_table_btn btn-lang" data-id="<?php echo $cd['blog-categories']['category_key'];?>" data-toggle="modal" data-target="#defaultModal">EDIT</button>
        <button onclick="DeleteCategory('<?php echo $cd['blog-categories']['category_key'];?>','hide');" type="button" class="btn bg-danger admn_table_btn">DELETE</button>
    </td>
</tr>