<tr class="setting-banlist" id="IPID_<?php echo $cd['user']['id']?>" data_selected="<?php echo($cd['user']['id']) ?>">
   <td><input type="checkbox" id="check-data-<?php echo($cd['user']['id']) ?>" class="delete-checkbox filled-in"><label for="check-data-<?php echo($cd['user']['id']) ?>"></label></td>
   <td><?php echo $cd['user']['id']?></td>
   <td>
      <div class="ajax-time" title="<?php echo date('c',$cd['user']['time']); ?>">
         <?php echo ToDate($cd['user']['time']);?>
      </div>
   </td>
   <td>
     <?php echo $cd['user']['value']?>
   </td>
   <td>
      <a href="javascript:void(0)" class="btn bg-danger admn_table_btn" onclick="DeleteBan(<?php echo $cd['user']['id']; ?>,'hide')">Delete</a>
   </td>
</tr>